steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -t
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/drivebatch:$COMMIT_SHA
      - .
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/drivebatch:$COMMIT_SHA
images:
  - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/drivebatch:$COMMIT_SHA
substitutions:
  _REGION: europe-west3
  _REPOSITORY: drivebatch
options:
  logging: CLOUD_LOGGING_ONLY
